初步完成了会员仪表盘的开发
2455DD/Library-Management-Backend pull request #28
Opened 2022-05-20 07:13 UTC by SmilingCatt

2022-05-20 07:17 UTC, SmilingCatt commented
修改了数据库，在user表中添加了lastReturn列，用于存储最后归还的书本id

2022-05-20 15:00 UTC, 2455DD requested changes

2022-05-20 15:00 UTC, 2455DD commented on services/member.go
> +		if err := tx.Where("user_id = ?", userId).Find(&borrowBooks).Error; err != nil {
这个不是"现在"借阅的图书量, 是"历史上"借阅的图书量, borrow表里会存以前的记录

2022-05-20 15:00 UTC, 2455DD commented on services/member.go
> +		if err := tx.Where("user_id = ?", userId).Find(&reserveBooks).Error; err != nil {
與上面同理,有些已經取消的預定也會被記錄

2022-05-21 05:35 UTC, SmilingCatt commented on services/member.go
> +		if err := tx.Where("user_id = ?", userId).Find(&reserveBooks).Error; err != nil {
今天仔细想想实现的是是把数据库里已经记录的东西读了出来，也就是历史的借阅量和预定量了

2022-05-21 11:19 UTC, 2455DD requested changes

2022-05-21 11:19 UTC, 2455DD commented on services/member.go
> +func (agent *DBAgent) CountHistoryBorrowedBooks(userId int) StatusResult {
你误会了......我之前的意思是你的接口和需求是对的,但你的实现不对,你要加一个Where()来判断查出来的这些数据中哪些是你要的.....下面同理

2022-05-21 11:51 UTC, SmilingCatt commented on services/member.go
> +func (agent *DBAgent) CountHistoryBorrowedBooks(userId int) StatusResult {
emmm...我的理解是borrow和reserve数据库里无论end_time有没有值都算是他历史借过的书和预定的书，然后就可以直接根据user_id查找数据库，把数量算出来就得到了历史借过书和预定书的数量然后返回给前端就可以了。还需要别的什么条件吗...

2022-05-21 14:53 UTC, 2455DD commented on services/member.go
> +func (agent *DBAgent) CountHistoryBorrowedBooks(userId int) StatusResult {
是这样的,我的理解是
1. CurrentBorrow显示的是**现在已借且未还**的书
(aka `endtime IS NONE` )
2. 我再看了一下, 可能是我对Requirement理解不到位, 把老师的原话和给的样例图复制出来你看一下
> 2. Reader Dashboard
>     1. Current Borrowed books
>     2. Last Return Books
>     3. Fine Amount (total)
>     4. Reserve Status

![](https://s2.loli.net/2022/05/21/nYRQk8g7JTK3hGo.png)

2022-05-21 15:12 UTC, SmilingCatt commented on services/member.go
> +func (agent *DBAgent) CountHistoryBorrowedBooks(userId int) StatusResult {
也就是说，我需要改的地方就是借阅这块只显示当前借阅但未归还的图书数量，预定这块只显示当前预定但未借阅或者取消预定的图书数量是吧（不是很理解这个Reserve Status是什么意思），已经完成的借阅和预定就忽略。这样可以吗

2022-05-22 03:47 UTC, 2455DD commented on services/member.go
> +func (agent *DBAgent) CountHistoryBorrowedBooks(userId int) StatusResult {
整体上就按照上面那个样例来写吧...
Reserve Status我的猜测是指现在有几个还活跃的Reservation,有几个Canceled的Reservation

2022-05-22 16:04 UTC, 2455DD approved these changes

2022-05-22 16:04 UTC, merged